<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( 'Gutentor_Template_Library_Block_Woocommerce' ) ) {

	/**
	 * Functions related to Video_Popup
	 * @package Gutentor
	 * @since 1.0.1
	 *
	 */

	class Gutentor_Template_Library_Block_Woocommerce extends Gutentor_Template_Library_Base{

		/**
		 * Name of the block.
		 *
		 * @access protected
		 * @since 1.0.1
		 * @var string
		 */
		protected $block_name = 'p1';

		/**
		 * Gets an instance of this object.
		 * Prevents duplicate instances which avoid artefacts and improves performance.
		 *
		 * @static
		 * @access public
		 * @since 1.0.1
		 * @return object
		 */
		public static function get_instance() {

			// Store the instance locally to avoid private static replication
			static $instance = null;

			// Only run these methods if they haven't been ran previously
			if ( null === $instance ) {
				$instance = new self();
			}

			// Always return the instance
			return $instance;

		}

		/**
         * Load block library
         * Used for blog template loading
         *
         * @since      1.1.5
         * @package    Gutentor
         * @author     Gutentor <info@gutentor.com>
         *
         * @param $templates_list array
         * @return array
         */
        public function add_block_template_library( $templates_list ){

            $block_library_list = array(

                array(
					'title'				=> __( 'Product 1', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array( 'woo', 'woocommerce','product 1' ),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-1/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-1/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-1/#product-1',
				),
				array(
					'title'				=> __( 'Product 2', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array( 'woo', 'woocommerce','product 2'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-2/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-2/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-1/#product-2',
				),
				array(
					'title'				=> __( 'Product 3', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array( 'woo', 'woocommerce','product 3' ),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-3/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-3/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-1/#product-3',
				),
				 array(
					'title'				=> __( 'Product 4', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array( 'woo', 'woocommerce','product 4' ),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-4/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-4/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-1/#product-4',
				),
				array(
					'title'				=> __( 'Product 5', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array( 'woo', 'woocommerce','product 5' ),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-5/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-5/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-2/#product-5',
				),
				array(
					'title'				=> __( 'Product 6', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 6'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-6/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-6/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-2/#product-6',
				),
				array(
					'title'				=> __( 'Product 7', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 7'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-7/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-7/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-2/#product-7',
				),
				array(
					'title'				=> __( 'Product 8', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 8'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-8/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-8/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-2/#product-8',
				),
				array(
					'title'				=> __( 'Product 9', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 9'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-9/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-9/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/post-feature-single/#product-9',
				),
				array(
					'title'				=> __( 'Product 10', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 10'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-10/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-10/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/2-column/#product-10',
				),
				array(
					'title'				=> __( 'Product 11', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 11'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-11/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-11/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/2-column/#product-11',
				),
				array(
					'title'				=> __( 'Product 12', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 12'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-12/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-12/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/2-column/#product-12',
				),
				array(
					'title'				=> __( 'Product 13', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 13'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-13/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-13/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/3-column/#product-13',
				),
				array(
					'title'				=> __( 'Product 14', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 14'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-14/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-14/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/3-column/#product-14',
				),
				array(
					'title'				=> __( 'Product 15', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 15'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-15/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-15/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/3-column/#product-15',
				),
				array(
					'title'				=> __( 'Product 16', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 16'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-16/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-16/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/3-column/#product-16',
				),
				array(
					'title'				=> __( 'Product 17', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 17'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-17/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-17/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/3-column/#product-17',
				),
				array(
					'title'				=> __( 'Product 18', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 18'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-18/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-18/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/3-column/#product-18',
				),
				array(
					'title'				=> __( 'Product 19', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 19'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-19/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-19/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/4-column/#product-19',
				),
				array(
					'title'				=> __( 'Product 20', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 20'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-20/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-20/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/4-column/#product-20',
				),
				array(
					'title'				=> __( 'Product 21', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 21'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-21/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-21/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/4-column/#product-21',
				),
				array(
					'title'				=> __( 'Product 22', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 22'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-22/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-22/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/4-column/#product-22',
				),
				array(
					'title'				=> __( 'Product 23', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 23'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-23/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-23/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/4-column/#product-23',
				),
				array(
					'title'				=> __( 'Product 24', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 24'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-24/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-24/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/4-column/#product-24',
				),
				array(
					'title'				=> __( 'Product 25', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 25'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-25/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-25/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/4-column/#product-25',
				),
				array(
					'title'				=> __( 'Product 26', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 26'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-26/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-26/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/4-column/#product-26',
				),
				array(
					'title'				=> __( 'Product 27', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 27'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-27/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-27/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/4-column/#product-27',
				),
				array(
					'title'				=> __( 'Product 28', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 28'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-28/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-28/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/4-column/#product-28',
				),
				array(
					'title'				=> __( 'Product 29', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 29'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-29/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-29/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/4-column/#product-29',
				),
				array(
					'title'				=> __( 'Product 30', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 30'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-30/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-30/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-30',
				),
				array(
					'title'				=> __( 'Product 31', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 31'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-31/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-31/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-31',
				),
				array(
					'title'				=> __( 'Product 32', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 32'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-32/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-32/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-32',
				),
				array(
					'title'				=> __( 'Product 33', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 33'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-33/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-33/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-33',
				),
				array(
					'title'				=> __( 'Product 34', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 34'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-34/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-34/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-34',
				),
				array(
					'title'				=> __( 'Product 35', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 35'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-35/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-35/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-35',
				),
				array(
					'title'				=> __( 'Product 36', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 36'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-36/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-36/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-36',
				),
				array(
					'title'				=> __( 'Product 37', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 37'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-37/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-37/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-37',
				),
				array(
					'title'				=> __( 'Product 38', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 38'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-38/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-38/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-38',
				),
				array(
					'title'				=> __( 'Product 39', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 39'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-39/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-39/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-39',
				),
				array(
					'title'				=> __( 'Product 40', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 40'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-40/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-40/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-40',
				),
				array(
					'title'				=> __( 'Product 41', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 41'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-41/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-41/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-41',
				),
				array(
					'title'				=> __( 'Product 42', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 42'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-42/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-42/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/5-column/#product-42',
				),
				array(
					'title'				=> __( 'Product 43', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 43'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-43/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-43/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/6-column/#product-43',
				),
				array(
					'title'				=> __( 'Product 44', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 44'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-44/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-44/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/6-column/#product-44',
				),
				array(
					'title'				=> __( 'Product 45', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 45'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-45/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-45/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/6-column/#product-45',
				),
				array(
					'title'				=> __( 'Product 46', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 46'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-46/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-46/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/6-column/#product-46',
				),
				array(
					'title'				=> __( 'Product 47', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 47'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-47/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-47/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/6-column/#product-47',
				),
				array(
					'title'				=> __( 'Product 48', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 48'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-48/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-48/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/6-column/#product-48',
				),
				array(
					'title'				=> __( 'Product 49', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 49'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-49/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-49/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/6-column/#product-49',
				),
				array(
					'title'				=> __( 'Product 50', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 50'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-50/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-50/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/6-column/#product-50',
				),
				array(
					'title'				=> __( 'Product 51', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 51'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-51/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-51/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/6-column/#product-51',
				),
				array(
					'title'				=> __( 'Product 52', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 52'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-52/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-52/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/duplex-product-1/#product-52',
				),
				array(
					'title'				=> __( 'Product 53', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 53'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-53/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-53/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/duplex-product-1/#product-53',
				),
				array(
					'title'				=> __( 'Product 54', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 54'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-54/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-54/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/duplex-product-2/#product-54',
				),
				array(
					'title'				=> __( 'Product 55', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 55'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-55/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-55/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/duplex-product-2/#product-55',
				),
				array(
					'title'				=> __( 'Product 56', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 56'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-56/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-56/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-carousel-1/#product-56',
				),
				array(
					'title'				=> __( 'Product 57', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 57'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-57/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-57/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-carousel-1/#product-57',
				),
				array(
					'title'				=> __( 'Product 58', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 58'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-58/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-58/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-carousel-1/#product-58',
				),
				array(
					'title'				=> __( 'Product 59', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 59'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-59/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-59/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-carousel-1/#product-59',
				),
				array(
					'title'				=> __( 'Product 60', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 60'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-60/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-60/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-carousel-2/#product-60',
				),
				array(
					'title'				=> __( 'Product 61', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 61'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-61/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-61/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-carousel-2/#product-61',
				),
				array(
					'title'				=> __( 'Product 62', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 62'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-62/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-62/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-carousel-2/#product-62',
				),
				array(
					'title'				=> __( 'Product 63', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 63'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-63/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-63/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/product-carousel-2/#product-63',
				),
				array(
					'title'				=> __( 'Product 64', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 64'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-64/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-64/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-1/#product-64',
				),
				array(
					'title'				=> __( 'Product 65', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 65'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-65/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-65/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-1/#product-65',
				),
				array(
					'title'				=> __( 'Product 66', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 66'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-66/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-66/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-1/#product-66',
				),
				array(
					'title'				=> __( 'Product 67', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 67'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-67/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-67/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-1/#product-67',
				),
				array(
					'title'				=> __( 'Product 68', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 68'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-68/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-68/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-1/#product-68',
				),
				array(
					'title'				=> __( 'Product 69', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 69'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-69/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-69/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-1/#product-69',
				),
				array(
					'title'				=> __( 'Product 70', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 70'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-70/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-70/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-1/#product-70',
				),
				array(
					'title'				=> __( 'Product 71', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 71'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-71/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-71/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-2/#product-71',
				),
				array(
					'title'				=> __( 'Product 72', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 72'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-72/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-72/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-2/#product-72',
				),
				array(
					'title'				=> __( 'Product 73', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 73'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-73/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-73/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-2/#product-73',
				),
				array(
					'title'				=> __( 'Product 74', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 74'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-74/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-74/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-2/#product-74',
				),
				array(
					'title'				=> __( 'Product 75', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 75'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-75/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-75/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-2/#product-75',
				),
				array(
					'title'				=> __( 'Product 76', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 76'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-76/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-76/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-2/#product-76',
				),
				array(
					'title'				=> __( 'Product 77', 'gutentor' ),
					'type'				=> 'block',
					'author'			=> __( 'Gutentor', 'gutentor' ),
					'keywords'			=> array('woo', 'woocommerce','product 77'),
					'categories'		=> array( 'woocommerce' ),
					'template_url'		=> GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-77/template.json',
					'screenshot_url'    => GUTENTOR_TEMPLATE_LIBRARY_GUTENTOR_URL.'template-data/module/woocommerce/product-77/screenshot.jpg',
					'demo_url'    => 'https://www.demo.gutentor.com/woocommerce/advanced-product-2/#product-77',
				),
				
				
				
				
				
				
				
				
				
				
                
            );

            return array_merge_recursive( $templates_list, $block_library_list );
        }
	}
}
Gutentor_Template_Library_Block_Woocommerce::get_instance()->run();